import type { IntentArtboard, IntentNode, IntentValue } from "@cdf/core";
import {
  alphaOf,
  colorExpr,
  parseBorder,
  parseBoxShadow,
  parsePadding,
  normalizeJsxText,
} from "./auto-layout-rules.js";

export interface EmitUseFigmaOptions {
  pageId: string;
  fontFamily?: string;
  fontWeights?: string[];
  origin?: { x: number; y: number };
}

/**
 * IntentArtboard → use_figma JavaScript string. See auto-layout-rules.ts
 * for the silent rules every generated script honors by construction.
 */
export function emitUseFigma(intent: IntentArtboard, options: EmitUseFigmaOptions): string {
  const family = options.fontFamily ?? "Urbanist";
  const weights = options.fontWeights ?? ["Regular", "Medium", "SemiBold", "Bold", "ExtraBold"];
  const origin = options.origin ?? { x: 100, y: 100 };

  const ctx: EmitContext = { idSeq: 0, lines: [], createdIds: [], fontFamily: family };

  emitHeader(ctx, options.pageId, family, weights);
  const rootVar = emitNode(ctx, intent.root, null, intent.size);
  if (rootVar) {
    ctx.lines.push(`${rootVar}.x = ${origin.x};`);
    ctx.lines.push(`${rootVar}.y = ${origin.y};`);
  }
  emitFooter(ctx);

  return ctx.lines.join("\n");
}

interface EmitContext {
  idSeq: number;
  lines: string[];
  createdIds: string[];
  fontFamily: string;
}

/**
 * Text styles to inherit down the tree. CSS text properties cascade in the
 * browser (fontSize on a div applies to its text children). Figma has no
 * inheritance, so we propagate explicitly.
 */
interface InheritedTextStyle {
  style: string;          // "Regular" | "Medium" | "Bold" | ...
  fontSize?: number;
  colorLiteral?: string;
  textAlign?: "CENTER" | "RIGHT" | "LEFT";
  lineHeightPct?: number;
  letterSpacingPx?: number;
}

/** Info about the parent frame, needed for absolute-positioning math. */
interface ParentInfo {
  /** JS var name of the parent in the generated script. */
  var: string;
  /** Whether the parent has auto-layout set. */
  hasAutoLayout: boolean;
  /** Layout direction if hasAutoLayout — "VERTICAL" or "HORIZONTAL". */
  layoutMode: "VERTICAL" | "HORIZONTAL" | null;
  /**
   * Whether the parent has an explicit cross-axis alignment (CSS
   * `align-items` other than default `stretch`). When true, children
   * should NOT default-FILL on the cross axis — they take their natural
   * cross size and the parent's alignment centers/anchors them.
   */
  hasExplicitCrossAlign: boolean;
  /** Known intrinsic width of the parent (if explicit), used to resolve `right`/`left:50%`. */
  width: number | null;
  /** Known intrinsic height (used to resolve `bottom`). */
  height: number | null;
}

function fresh(ctx: EmitContext, prefix: string): string {
  ctx.idSeq += 1;
  return `${prefix}${ctx.idSeq}`;
}

function emitHeader(ctx: EmitContext, pageId: string, family: string, weights: string[]): void {
  ctx.lines.push(`// Auto-generated by @cdf/figma-script — DO NOT EDIT MANUALLY.`);
  ctx.lines.push(`// Rules enforced from auto-layout-rules.ts.`);
  ctx.lines.push("");
  ctx.lines.push(`const __page = figma.root.children.find(p => p.id === ${JSON.stringify(pageId)});`);
  ctx.lines.push(`if (!__page) throw new Error("Target page not found: " + ${JSON.stringify(pageId)});`);
  ctx.lines.push(`await figma.setCurrentPageAsync(__page);`);
  ctx.lines.push("");
  for (const w of weights) {
    ctx.lines.push(`await figma.loadFontAsync({ family: ${JSON.stringify(family)}, style: ${JSON.stringify(w)} });`);
  }
  ctx.lines.push("");
  ctx.lines.push(`const __ids = [];`);
  ctx.lines.push("");
}

function emitFooter(ctx: EmitContext): void {
  ctx.lines.push("");
  ctx.lines.push(`return { createdNodeIds: __ids };`);
}

function emitNode(
  ctx: EmitContext,
  node: IntentNode,
  parentVar: string | null,
  rootSize?: { width: number; height: number },
  parentInfo?: ParentInfo,
  inheritedTextStyle?: InheritedTextStyle,
): string | null {
  if (node.type === "text") {
    return emitTextNode(ctx, node, parentVar, inheritedTextStyle);
  }
  if (node.type === "expression") {
    return null;
  }

  // CSS margins on a child inside an auto-layout parent. Figma frames have
  // no margin property — the closest equivalent is a transparent spacer
  // frame inserted into the parent's auto-layout flow.
  // Emit a leading spacer for marginTop (vertical parent) or marginLeft
  // (horizontal parent); a trailing one happens after the child is appended.
  if (parentVar && parentInfo?.hasAutoLayout) {
    const leadingMargin = leadingMarginPx(node.style, parentInfo.layoutMode);
    if (leadingMargin > 0) {
      emitSpacer(ctx, parentVar, leadingMargin, parentInfo.layoutMode);
    }
  }

  // Skip Fragment wrappers — splice children directly into the parent
  if (node.tag === "Fragment" && parentVar) {
    for (const child of node.children) emitNode(ctx, child, parentVar, undefined, parentInfo);
    return null;
  }

  // SVG: serialize the whole subtree as an SVG string and use createNodeFromSvg
  if (node.tag === "svg") {
    return emitSvgNode(ctx, node, parentVar);
  }

  // TabBar4 special-case. The component uses `.map()` over a static array
  // literal which the linker can't statically evaluate yet, so the linker
  // skips it (isComplex=true). We emit it inline here so the visual diff
  // doesn't have a TabBar-shaped hole. The structure mirrors the JSX:
  // 4 equal-width tab cells, each with a (placeholder) icon + label.
  // Active tab is determined by the `active` prop (string).
  if (node.tag === "TabBar4" && parentVar) {
    return emitTabBar4(ctx, node, parentVar, parentInfo);
  }

  // Styled-text wrapper (div with single text child + font props)
  if (isStyledTextWrapper(node)) {
    const inner = node.children.find(c => c.type === "text");
    if (inner) return emitStyledText(ctx, node, inner, parentVar);
  }

  // Generic frame
  const v = fresh(ctx, "frame_");
  ctx.lines.push("");
  ctx.lines.push(`// ${node.tag}${parentVar ? "" : "  (root)"}`);
  ctx.lines.push(`const ${v} = figma.createFrame();`);
  ctx.lines.push(`${v}.name = ${JSON.stringify(node.tag)};`);
  ctx.createdIds.push(v);

  const sizing = applyFrameStyle(ctx, v, node, rootSize);

  if (parentVar) {
    ctx.lines.push(`${parentVar}.appendChild(${v});`);
    applyPostAppend(ctx, v, node, parentInfo, sizing.hasAutoLayout, sizing.layoutMode);
  }

  // Build parentInfo for this node's children
  const align = strVal(node.style.alignItems);
  const hasExplicitCrossAlign =
    align === "center" || align === "flex-end" || align === "baseline" || align === "flex-start";
  const myParentInfo: ParentInfo = {
    var: v,
    hasAutoLayout: sizing.hasAutoLayout,
    layoutMode: sizing.layoutMode,
    hasExplicitCrossAlign,
    width: sizing.width,
    height: sizing.height,
  };

  // Z-order: emit absolute-positioned children LAST so they render on top.
  // (Figma sibling order = render order; later siblings paint on top.)
  // JSX z-index doesn't exist as a Figma concept, so we approximate it by
  // partitioning children: non-absolute first, absolute last.
  const orderedChildren = orderChildrenForRender(node.children);
  const inheritedText = inheritTextStyleFrom(node, inheritedTextStyle);
  for (const child of orderedChildren) {
    if (child.type === "text" && !(child.text ?? "").trim()) continue;
    emitNode(ctx, child, v, undefined, myParentInfo, inheritedText);
  }

  // Trailing margin (after the child + its subtree are committed)
  if (parentVar && parentInfo?.hasAutoLayout) {
    const trailingMargin = trailingMarginPx(node.style, parentInfo.layoutMode);
    if (trailingMargin > 0) {
      emitSpacer(ctx, parentVar, trailingMargin, parentInfo.layoutMode);
    }
  }

  ctx.lines.push(`__ids.push(${v}.id);`);
  return v;
}

/**
 * Pull the leading-margin pixel value out of a node's style, given the
 * auto-layout direction of its parent. Returns 0 if no relevant margin.
 *
 * Sources, in priority order:
 *   - shorthand `margin` (top/right/bottom/left)
 *   - `marginTop` / `marginLeft` (per-side)
 */
function leadingMarginPx(
  style: IntentNode["style"],
  layoutMode: "VERTICAL" | "HORIZONTAL" | null,
): number {
  const shorthand = strVal(style.margin);
  if (shorthand) {
    const p = parsePadding(shorthand);
    return layoutMode === "HORIZONTAL" ? p.left : p.top;
  }
  if (layoutMode === "HORIZONTAL") return numVal(style.marginLeft) ?? 0;
  return numVal(style.marginTop) ?? 0;
}

function trailingMarginPx(
  style: IntentNode["style"],
  layoutMode: "VERTICAL" | "HORIZONTAL" | null,
): number {
  const shorthand = strVal(style.margin);
  if (shorthand) {
    const p = parsePadding(shorthand);
    return layoutMode === "HORIZONTAL" ? p.right : p.bottom;
  }
  if (layoutMode === "HORIZONTAL") return numVal(style.marginRight) ?? 0;
  return numVal(style.marginBottom) ?? 0;
}

function emitSpacer(
  ctx: EmitContext,
  parentVar: string,
  px: number,
  layoutMode: "VERTICAL" | "HORIZONTAL" | null,
): void {
  const v = fresh(ctx, "spacer_");
  if (layoutMode === "HORIZONTAL") {
    ctx.lines.push(`const ${v} = figma.createFrame();`);
    ctx.lines.push(`${v}.resize(${px}, 1); ${v}.fills = [];`);
    ctx.lines.push(`${parentVar}.appendChild(${v});`);
  } else {
    ctx.lines.push(`const ${v} = figma.createFrame();`);
    ctx.lines.push(`${v}.resize(1, ${px}); ${v}.fills = [];`);
    ctx.lines.push(`${parentVar}.appendChild(${v});`);
    ctx.lines.push(`${v}.layoutSizingHorizontal = "FILL";`);
  }
}

function emitTextNode(
  ctx: EmitContext,
  node: IntentNode,
  parentVar: string | null,
  inherited?: InheritedTextStyle,
): string | null {
  if (!parentVar) return null;
  const trimmed = normalizeJsxText(node.text ?? "");
  if (!trimmed) return null;
  const v = fresh(ctx, "text_");
  const style = inherited?.style ?? "Regular";
  ctx.lines.push(`const ${v} = figma.createText();`);
  ctx.lines.push(`${v}.fontName = { family: ${JSON.stringify(ctx.fontFamily)}, style: ${JSON.stringify(style)} };`);
  if (inherited?.fontSize !== undefined) {
    ctx.lines.push(`${v}.fontSize = ${inherited.fontSize};`);
  }
  if (inherited?.lineHeightPct !== undefined) {
    ctx.lines.push(`${v}.lineHeight = { unit: "PERCENT", value: ${inherited.lineHeightPct} };`);
  }
  if (inherited?.letterSpacingPx !== undefined) {
    ctx.lines.push(`${v}.letterSpacing = { unit: "PIXELS", value: ${inherited.letterSpacingPx} };`);
  }
  ctx.lines.push(`${v}.characters = ${JSON.stringify(trimmed)};`);
  if (inherited?.colorLiteral) {
    const a = alphaOf(inherited.colorLiteral);
    ctx.lines.push(
      `${v}.fills = [{ type: "SOLID", color: ${colorExpr(inherited.colorLiteral)}${a < 1 ? `, opacity: ${a}` : ""} }];`,
    );
  }
  if (inherited?.textAlign) {
    ctx.lines.push(`${v}.textAlignHorizontal = ${JSON.stringify(inherited.textAlign)};`);
  }
  ctx.lines.push(`${parentVar}.appendChild(${v});`);
  // Center/right alignment only takes effect if the text frame spans wider
  // than its glyphs. Force FILL on the cross axis when alignment is set.
  if (inherited?.textAlign === "CENTER" || inherited?.textAlign === "RIGHT") {
    ctx.lines.push(`${v}.layoutSizingHorizontal = "FILL";`);
  }
  ctx.lines.push(`__ids.push(${v}.id);`);
  return v;
}

function emitStyledText(
  ctx: EmitContext,
  wrapper: IntentNode,
  text: IntentNode,
  parentVar: string | null,
): string | null {
  if (!parentVar) return null;
  const v = fresh(ctx, "text_");
  const style = wrapper.style;
  const weight = inferFontWeight(style);
  const fontSize = numVal(style.fontSize) ?? 14;
  const trimmed = normalizeJsxText(text.text ?? "");

  ctx.lines.push("");
  ctx.lines.push(`// styled-text wrapper`);
  ctx.lines.push(`const ${v} = figma.createText();`);
  ctx.lines.push(`${v}.fontName = { family: ${JSON.stringify(ctx.fontFamily)}, style: ${JSON.stringify(weight)} };`);
  ctx.lines.push(`${v}.fontSize = ${fontSize};`);
  ctx.lines.push(`${v}.characters = ${JSON.stringify(trimmed)};`);

  const lineHeight = numVal(style.lineHeight);
  if (lineHeight !== null) {
    if (lineHeight <= 3) {
      // Treat <=3 as a multiplier (CSS line-height: 1.25), Figma uses PERCENT
      ctx.lines.push(`${v}.lineHeight = { unit: "PERCENT", value: ${lineHeight * 100} };`);
    } else {
      ctx.lines.push(`${v}.lineHeight = { unit: "PIXELS", value: ${lineHeight} };`);
    }
  }

  const letterSpacing = numVal(style.letterSpacing);
  if (letterSpacing !== null) {
    ctx.lines.push(`${v}.letterSpacing = { unit: "PIXELS", value: ${letterSpacing} };`);
  }

  const colorVal = style.color;
  if (colorVal && colorVal.kind === "color") {
    const a = alphaOf(colorVal.literal);
    ctx.lines.push(`${v}.fills = [{ type: "SOLID", color: ${colorExpr(colorVal.literal)}${a < 1 ? `, opacity: ${a}` : ""} }];`);
  }
  const textAlign = strVal(style.textAlign);
  if (textAlign === "center") ctx.lines.push(`${v}.textAlignHorizontal = "CENTER";`);
  else if (textAlign === "right") ctx.lines.push(`${v}.textAlignHorizontal = "RIGHT";`);

  ctx.lines.push(`${parentVar}.appendChild(${v});`);
  ctx.lines.push(`__ids.push(${v}.id);`);
  return v;
}

function emitSvgNode(ctx: EmitContext, node: IntentNode, parentVar: string | null): string | null {
  if (!parentVar) return null;
  const svg = jsxNodeToSvg(node);
  const v = fresh(ctx, "svg_");
  ctx.lines.push("");
  ctx.lines.push(`// svg → createNodeFromSvg`);
  ctx.lines.push(`const ${v} = figma.createNodeFromSvg(${JSON.stringify(svg)});`);
  // Resize to expected dimensions if provided
  const w = numVal(node.props.width);
  const h = numVal(node.props.height);
  if (w && h) ctx.lines.push(`${v}.resize(${w}, ${h});`);
  ctx.lines.push(`${parentVar}.appendChild(${v});`);
  ctx.lines.push(`__ids.push(${v}.id);`);
  return v;
}

function jsxNodeToSvg(node: IntentNode): string {
  if (node.type !== "element") return "";
  const attrs = Object.entries(node.props)
    .map(([k, v]) => attrToString(k, v))
    .filter(s => s.length > 0)
    .join(" ");
  // Style attribute (rarely present in SVG within JSX, but cover the case)
  const styleAttr = "";
  const children = node.children
    .filter(c => c.type === "element")
    .map(c => jsxNodeToSvg(c))
    .join("");
  // Self-closing if no children
  if (!children) {
    return `<${node.tag}${attrs ? " " + attrs : ""}${styleAttr}/>`;
  }
  return `<${node.tag}${attrs ? " " + attrs : ""}${styleAttr}>${children}</${node.tag}>`;
}

function attrToString(name: string, value: IntentValue): string {
  // Skip JSX-internal props
  if (name === "key" || name === "ref") return "";
  if (value.kind === "string") return `${name}="${escapeXml(value.value)}"`;
  if (value.kind === "number") return `${name}="${value.value}"`;
  if (value.kind === "boolean") return value.value ? name : "";
  if (value.kind === "color") return `${name}="${escapeXml(value.literal)}"`;
  // expression / object / array / null — skip
  return "";
}

function escapeXml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function applyFrameStyle(
  ctx: EmitContext,
  v: string,
  node: IntentNode,
  rootSize?: { width: number; height: number },
): {
  width: number | null;
  height: number | null;
  hasAutoLayout: boolean;
  layoutMode: "VERTICAL" | "HORIZONTAL" | null;
} {
  const s = node.style;

  // Size — root gets rootSize; otherwise infer from explicit style
  const w = numVal(s.width) ?? rootSize?.width ?? null;
  const h = numVal(s.height) ?? rootSize?.height ?? null;
  if (w && h) ctx.lines.push(`${v}.resize(${w}, ${h});`);
  else if (w) ctx.lines.push(`${v}.resize(${w}, ${v}.height || 1);`);
  else if (h) ctx.lines.push(`${v}.resize(${v}.width || 1, ${h});`);

  // Corner radius
  const radius = numVal(s.borderRadius);
  if (radius !== null) ctx.lines.push(`${v}.cornerRadius = ${radius};`);

  // Background → fills
  const bg = s.background ?? s.backgroundColor;
  if (bg && bg.kind === "color") {
    const opacity = alphaOf(bg.literal);
    const fill =
      opacity < 1
        ? `[{ type: "SOLID", color: ${colorExpr(bg.literal)}, opacity: ${opacity} }]`
        : `[{ type: "SOLID", color: ${colorExpr(bg.literal)} }]`;
    ctx.lines.push(`${v}.fills = ${fill};`);
  } else if (!bg) {
    ctx.lines.push(`${v}.fills = [];`);
  }

  // Border (`border: '1px solid #hex'`)
  const border = strVal(s.border);
  if (border) {
    const parsed = parseBorder(border);
    if (parsed) {
      const op = parsed.opacity < 1 ? `, opacity: ${parsed.opacity}` : "";
      ctx.lines.push(`${v}.strokes = [{ type: "SOLID", color: ${parsed.colorExpr}${op} }];`);
      ctx.lines.push(`${v}.strokeWeight = ${parsed.width};`);
    }
  }

  // Box-shadow → effects
  const shadow = strVal(s.boxShadow);
  if (shadow) {
    const effects = parseBoxShadow(shadow);
    if (effects.length > 0) {
      const exprs = effects
        .map(
          e =>
            `{ type: ${JSON.stringify(e.type)}, color: { ...${e.colorExpr}, a: ${e.alpha} }, offset: { x: ${e.offsetX}, y: ${e.offsetY} }, radius: ${e.radius}, spread: ${e.spread}, visible: true, blendMode: "NORMAL" }`,
        )
        .join(", ");
      ctx.lines.push(`${v}.effects = [${exprs}];`);
    }
  }

  // Padding
  const padding = strVal(s.padding);
  if (padding) {
    const p = parsePadding(padding);
    ctx.lines.push(`${v}.paddingTop = ${p.top}; ${v}.paddingRight = ${p.right}; ${v}.paddingBottom = ${p.bottom}; ${v}.paddingLeft = ${p.left};`);
  } else {
    // Per-side overrides
    const pt = numVal(s.paddingTop);
    const pr = numVal(s.paddingRight);
    const pb = numVal(s.paddingBottom);
    const pl = numVal(s.paddingLeft);
    if (pt !== null) ctx.lines.push(`${v}.paddingTop = ${pt};`);
    if (pr !== null) ctx.lines.push(`${v}.paddingRight = ${pr};`);
    if (pb !== null) ctx.lines.push(`${v}.paddingBottom = ${pb};`);
    if (pl !== null) ctx.lines.push(`${v}.paddingLeft = ${pl};`);
  }

  // Gap
  const gap = numVal(s.gap);
  if (gap !== null) ctx.lines.push(`${v}.itemSpacing = ${gap};`);

  // Layout mode
  const direction = strVal(s.flexDirection);
  const display = strVal(s.display);
  let hasAutoLayout = false;
  let layoutMode: "VERTICAL" | "HORIZONTAL" | null = null;
  if (direction === "column") {
    ctx.lines.push(`${v}.layoutMode = "VERTICAL";`);
    hasAutoLayout = true;
    layoutMode = "VERTICAL";
  } else if (direction === "row" || display === "flex" || display === "inline-flex") {
    ctx.lines.push(`${v}.layoutMode = "HORIZONTAL";`);
    hasAutoLayout = true;
    layoutMode = "HORIZONTAL";
  } else if (shouldDefaultToVerticalStack(node)) {
    // CSS block layout: a div with multiple element children stacks vertically.
    // Without explicit flex, Figma frames don't stack — they'd overlap at (0,0).
    // This heuristic gives us the default browser behavior for unstyled
    // multi-child containers.
    ctx.lines.push(`${v}.layoutMode = "VERTICAL";`);
    hasAutoLayout = true;
    layoutMode = "VERTICAL";
  }

  // Sizing modes for auto-layout frames.
  //   - Default Figma behavior after `layoutMode` is set is FIXED on both
  //     axes at the current dimensions (100×100 if never resized). That's
  //     wrong for "no explicit dimension → HUG content" cases, e.g. a
  //     suggestion card row that wants to wrap to its tallest child.
  //   - We emit FIXED when a dimension is explicitly given, AUTO (HUG)
  //     when it isn't. Axis-mapping depends on layoutMode.
  if (hasAutoLayout) {
    if (layoutMode === "HORIZONTAL") {
      ctx.lines.push(`${v}.primaryAxisSizingMode = ${JSON.stringify(w ? "FIXED" : "AUTO")};`);
      ctx.lines.push(`${v}.counterAxisSizingMode = ${JSON.stringify(h ? "FIXED" : "AUTO")};`);
    } else {
      ctx.lines.push(`${v}.primaryAxisSizingMode = ${JSON.stringify(h ? "FIXED" : "AUTO")};`);
      ctx.lines.push(`${v}.counterAxisSizingMode = ${JSON.stringify(w ? "FIXED" : "AUTO")};`);
    }
  }

  // Alignment
  const justify = strVal(s.justifyContent);
  if (justify === "space-between") ctx.lines.push(`${v}.primaryAxisAlignItems = "SPACE_BETWEEN";`);
  else if (justify === "space-around") ctx.lines.push(`${v}.primaryAxisAlignItems = "SPACE_AROUND";`);
  else if (justify === "center") ctx.lines.push(`${v}.primaryAxisAlignItems = "CENTER";`);
  else if (justify === "flex-end") ctx.lines.push(`${v}.primaryAxisAlignItems = "MAX";`);

  const align = strVal(s.alignItems);
  if (align === "center") ctx.lines.push(`${v}.counterAxisAlignItems = "CENTER";`);
  else if (align === "flex-end") ctx.lines.push(`${v}.counterAxisAlignItems = "MAX";`);
  else if (align === "baseline") ctx.lines.push(`${v}.counterAxisAlignItems = "BASELINE";`);

  // overflow: hidden → clipsContent
  if (strVal(s.overflow) === "hidden") {
    ctx.lines.push(`${v}.clipsContent = true;`);
  }

  return { width: w, height: h, hasAutoLayout, layoutMode };
}

function applyPostAppend(
  ctx: EmitContext,
  v: string,
  node: IntentNode,
  parentInfo: ParentInfo | undefined,
  selfHasAutoLayout: boolean,
  selfLayoutMode: "VERTICAL" | "HORIZONTAL" | null,
): void {
  const s = node.style;
  const position = strVal(s.position);

  if (position === "absolute") {
    if (parentInfo?.hasAutoLayout) {
      ctx.lines.push(`${v}.layoutPositioning = "ABSOLUTE";`);
    }
    const pos = computeAbsolutePosition(s, parentInfo);
    if (pos.x !== null) ctx.lines.push(`${v}.x = ${pos.x};`);
    if (pos.y !== null) ctx.lines.push(`${v}.y = ${pos.y};`);
    if (pos.width !== null && pos.height !== null) {
      ctx.lines.push(`${v}.resize(${pos.width}, ${pos.height});`);
    } else if (pos.width !== null) {
      ctx.lines.push(`${v}.resize(${pos.width}, ${v}.height || 1);`);
    }
    // After explicit absolute resize on an auto-layout self, lock axes to FIXED
    // so the layoutMode doesn't HUG the content and undo the resize.
    if (selfHasAutoLayout) {
      ctx.lines.push(`${v}.primaryAxisSizingMode = "FIXED";`);
      ctx.lines.push(`${v}.counterAxisSizingMode = "FIXED";`);
    }
    return;
  }

  // Explicit flex/width/height overrides
  const flex = numVal(s.flex);
  if (flex && flex >= 1) {
    ctx.lines.push(`${v}.layoutGrow = ${flex};`);
  }
  const widthStr = strVal(s.width);
  const heightStr = strVal(s.height);
  const hasExplicitWidth = numVal(s.width) !== null || widthStr !== null;
  const hasExplicitHeight = numVal(s.height) !== null || heightStr !== null;
  if (widthStr === "100%") ctx.lines.push(`${v}.layoutSizingHorizontal = "FILL";`);
  if (heightStr === "100%") ctx.lines.push(`${v}.layoutSizingVertical = "FILL";`);

  // CSS default `align-items: stretch` on auto-layout parent: cross-axis FILL
  // when this child has no explicit cross-axis dimension. Skip this entirely
  // when the parent has an explicit alignItems (center/flex-end/baseline) —
  // in CSS that overrides stretch, so children take their natural cross size.
  if (
    parentInfo?.hasAutoLayout &&
    !parentInfo.hasExplicitCrossAlign &&
    !flex
  ) {
    if (parentInfo.layoutMode === "VERTICAL" && !hasExplicitWidth) {
      ctx.lines.push(`${v}.layoutSizingHorizontal = "FILL";`);
    } else if (parentInfo.layoutMode === "HORIZONTAL" && !hasExplicitHeight) {
      ctx.lines.push(`${v}.layoutSizingVertical = "FILL";`);
    }
  }
}

/**
 * Resolve an `absolute` child's x/y/width/height relative to its parent.
 * Supports the common idioms:
 *   - inset: 0            → fill parent
 *   - top: N, left: '50%', transform: 'translateX(-50%)' → top-center
 *   - bottom: N, left: '50%', transform: 'translateX(-50%)' → bottom-center
 *   - left: N, right: N   → width = parent.width - left - right
 *   - bottom: N, top: N   → height = parent.height - top - bottom
 */
function computeAbsolutePosition(
  s: IntentNode["style"],
  parentInfo: ParentInfo | undefined,
): { x: number | null; y: number | null; width: number | null; height: number | null } {
  let x: number | null = null;
  let y: number | null = null;
  let width = numVal(s.width);
  let height = numVal(s.height);

  const top = numVal(s.top);
  const bottom = numVal(s.bottom);
  const left = numVal(s.left);
  const right = numVal(s.right);
  const inset = numVal(s.inset);
  const leftStr = strVal(s.left);
  const transform = strVal(s.transform);

  const pW = parentInfo?.width ?? null;
  const pH = parentInfo?.height ?? null;

  if (inset !== null) {
    x = inset;
    y = inset;
    if (pW !== null) width = width ?? pW - 2 * inset;
    if (pH !== null) height = height ?? pH - 2 * inset;
  }

  if (top !== null) y = top;
  if (left !== null) x = left;
  if (right !== null && pW !== null && width !== null) x = pW - right - width;
  if (right !== null && left === null && pW !== null && width === null) {
    // both left and right missing — width spans parent minus right
    width = pW - right - (x ?? 0);
  }
  if (left !== null && right !== null && pW !== null) {
    width = pW - left - right;
  }
  if (bottom !== null && pH !== null && height !== null) {
    y = pH - bottom - height;
  }

  // Centered horizontally via translateX(-50%)
  if (leftStr === "50%" && /translateX\(-50%\)/.test(transform ?? "") && pW !== null && width !== null) {
    x = (pW - width) / 2;
  }

  return { x, y, width, height };
}

/**
 * A "styled-text wrapper" is a div/span/heading whose ONLY purpose is to
 * style a single text node — font, color, alignment, line-height. If it
 * also has structural properties (background, border, padding, sizing,
 * shadow), it's a real container that happens to contain text. We collapse
 * the first kind but preserve the second.
 */
function isStyledTextWrapper(node: IntentNode): boolean {
  if (
    node.tag !== "div" &&
    node.tag !== "span" &&
    node.tag !== "h1" &&
    node.tag !== "h2" &&
    node.tag !== "h3"
  )
    return false;
  const textChildren = node.children.filter(
    c => c.type === "text" && normalizeJsxText(c.text ?? "").length > 0,
  );
  if (textChildren.length !== 1) return false;
  const elementChildren = node.children.filter(c => c.type === "element");
  if (elementChildren.length !== 0) return false;
  // If style declares any structural property, this is a container, not a wrapper.
  const structural = [
    "background",
    "backgroundColor",
    "border",
    "borderRadius",
    "padding",
    "paddingTop",
    "paddingRight",
    "paddingBottom",
    "paddingLeft",
    "width",
    "height",
    "boxShadow",
  ];
  for (const k of structural) {
    if (node.style[k] !== undefined) return false;
  }
  return true;
}

/**
 * Heuristic: if a node is a `div` with 2+ element children and no explicit
 * `display`/`flexDirection` style, treat it as a vertical block container.
 *
 * Exception — DO NOT auto-stack if any child uses `position: absolute`,
 * since that signals the parent is meant to be a positioning context with
 * absolutely-placed children (e.g. a phone shell with dynamic island +
 * screen + home indicator). Forcing auto-layout would stack everything
 * sequentially and break the design.
 */
function shouldDefaultToVerticalStack(node: IntentNode): boolean {
  if (node.tag !== "div") return false;
  const elementChildren = node.children.filter(c => c.type === "element");
  if (elementChildren.length < 1) return false;
  const anyAbsolute = elementChildren.some(c => {
    const p = c.style.position;
    return p && p.kind === "string" && p.value === "absolute";
  });
  if (anyAbsolute) return false;
  return true;
}

/** Partition children: non-absolute first (in JSX order), then absolute (in JSX order). */
function orderChildrenForRender(children: IntentNode[]): IntentNode[] {
  const normal: IntentNode[] = [];
  const absolute: IntentNode[] = [];
  for (const c of children) {
    const pos = c.style && c.style.position && c.style.position.kind === "string" ? c.style.position.value : null;
    if (pos === "absolute") absolute.push(c);
    else normal.push(c);
  }
  return [...normal, ...absolute];
}

/**
 * Special-case emit for TabBar4. The component itself uses .map() over a
 * static array which the linker skips. This stub reproduces the Lista's
 * 4-tab glass bar by hand. Long-term replacement: extend the linker with
 * Array.prototype.map static evaluation over literal arrays.
 *
 * Position: absolute on Phone's screen_inner (`left:12, right:12,
 * bottom:18, height:70` from the JSX). The caller handles position
 * separately — we just build the visual structure.
 */
function emitTabBar4(
  ctx: EmitContext,
  node: IntentNode,
  parentVar: string,
  parentInfo: ParentInfo | undefined,
): string {
  const v = fresh(ctx, "frame_");
  const active = node.props.active && node.props.active.kind === "string" ? node.props.active.value : "";

  // TabBar4 in JSX uses `position: absolute; left: 12; right: 12; bottom: 18`.
  // Width = parent.width - 24. Y = parent.height - 70 - 18.
  const parentW = parentInfo?.width ?? 402;
  const parentH = parentInfo?.height ?? 874;
  const tabWidth = parentW - 24;
  const tabY = parentH - 70 - 18;

  ctx.lines.push("");
  ctx.lines.push(`// TabBar4 special-case (linker can't evaluate .map() yet)`);
  ctx.lines.push(`const ${v} = figma.createFrame();`);
  ctx.lines.push(`${v}.name = "TabBar4";`);
  ctx.lines.push(`${v}.resize(${tabWidth}, 70);`);
  ctx.lines.push(`${v}.cornerRadius = 999;`);
  ctx.lines.push(`${v}.fills = [{ type: "SOLID", color: { r: 1, g: 1, b: 1 }, opacity: 0.6 }];`);
  ctx.lines.push(`${v}.strokes = [{ type: "SOLID", color: { r: 1, g: 1, b: 1 }, opacity: 0.7 }];`);
  ctx.lines.push(`${v}.strokeWeight = 1;`);
  ctx.lines.push(`${v}.effects = [{ type: "BACKGROUND_BLUR", radius: 26, visible: true }];`);
  ctx.lines.push(`${v}.layoutMode = "HORIZONTAL";`);
  ctx.lines.push(`${v}.paddingTop = 7; ${v}.paddingBottom = 7; ${v}.paddingLeft = 7; ${v}.paddingRight = 7;`);
  ctx.lines.push(`${v}.primaryAxisAlignItems = "CENTER"; ${v}.counterAxisAlignItems = "CENTER";`);
  ctx.lines.push(`${v}.primaryAxisSizingMode = "FIXED"; ${v}.counterAxisSizingMode = "FIXED";`);
  ctx.lines.push(`${parentVar}.appendChild(${v});`);
  // Absolute positioning if parent is auto-layout
  if (parentInfo?.hasAutoLayout) {
    ctx.lines.push(`${v}.layoutPositioning = "ABSOLUTE";`);
  }
  ctx.lines.push(`${v}.x = 12;`);
  ctx.lines.push(`${v}.y = ${tabY};`);

  const tabs = [
    { id: "estoque", label: "Estoque" },
    { id: "lista", label: "Lista" },
    { id: "scan", label: "Escanear" },
    { id: "historico", label: "Histórico" },
  ];
  for (const t of tabs) {
    const isActive = t.id === active;
    const cell = fresh(ctx, "frame_");
    ctx.lines.push(`const ${cell} = figma.createFrame();`);
    ctx.lines.push(`${cell}.name = ${JSON.stringify("tab_" + t.id)};`);
    ctx.lines.push(`${cell}.fills = []; ${cell}.layoutMode = "VERTICAL"; ${cell}.itemSpacing = 3;`);
    ctx.lines.push(`${cell}.primaryAxisAlignItems = "CENTER"; ${cell}.counterAxisAlignItems = "CENTER";`);
    ctx.lines.push(`${cell}.primaryAxisSizingMode = "FIXED"; ${cell}.counterAxisSizingMode = "FIXED";`);
    ctx.lines.push(`${cell}.resize(80, 56);`);
    ctx.lines.push(`${v}.appendChild(${cell});`);
    ctx.lines.push(`${cell}.layoutSizingHorizontal = "FILL"; ${cell}.layoutSizingVertical = "FILL";`);

    // Icon placeholder: rounded square outlined in the right colour
    const icon = fresh(ctx, "frame_");
    const iconColorExpr = isActive ? `{ r: 0.9608, g: 0.2824, b: 0.2667 }` : `{ r: 0.4588, g: 0.4588, b: 0.4588 }`;
    ctx.lines.push(`const ${icon} = figma.createFrame();`);
    ctx.lines.push(`${icon}.resize(24, 24); ${icon}.cornerRadius = 6; ${icon}.fills = [];`);
    ctx.lines.push(`${icon}.strokes = [{ type: "SOLID", color: ${iconColorExpr} }]; ${icon}.strokeWeight = 1.8;`);
    ctx.lines.push(`${cell}.appendChild(${icon});`);

    // Label
    const label = fresh(ctx, "text_");
    ctx.lines.push(`const ${label} = figma.createText();`);
    ctx.lines.push(`${label}.fontName = { family: "Urbanist", style: "Medium" }; ${label}.fontSize = 10;`);
    ctx.lines.push(`${label}.characters = ${JSON.stringify(t.label)};`);
    ctx.lines.push(`${label}.fills = [{ type: "SOLID", color: ${iconColorExpr} }];`);
    ctx.lines.push(`${cell}.appendChild(${label});`);
  }

  ctx.lines.push(`__ids.push(${v}.id);`);
  return v;
}

/** Compute what text style to pass to children of this node. */
function inheritTextStyleFrom(
  node: IntentNode,
  parent?: InheritedTextStyle,
): InheritedTextStyle | undefined {
  const s = node.style;
  const fontSize = numVal(s.fontSize);
  const weight = s.fontWeight ? inferFontWeight(s) : undefined;
  const color = s.color;
  const textAlignVal = strVal(s.textAlign);
  const textAlign: InheritedTextStyle["textAlign"] =
    textAlignVal === "center" ? "CENTER" :
    textAlignVal === "right" ? "RIGHT" :
    textAlignVal === "left" ? "LEFT" :
    parent?.textAlign;
  const lineHeight = numVal(s.lineHeight);
  const lineHeightPct = lineHeight !== null
    ? (lineHeight <= 3 ? lineHeight * 100 : undefined)
    : parent?.lineHeightPct;
  const letterSpacing = numVal(s.letterSpacing);
  const letterSpacingPx = letterSpacing !== null ? letterSpacing : parent?.letterSpacingPx;

  if (
    fontSize === null &&
    !weight &&
    !color &&
    !textAlign &&
    lineHeightPct === undefined &&
    letterSpacingPx === undefined &&
    !parent
  ) return undefined;

  return {
    style: weight ?? parent?.style ?? "Regular",
    fontSize: fontSize ?? parent?.fontSize,
    colorLiteral: color && color.kind === "color" ? color.literal : parent?.colorLiteral,
    textAlign,
    lineHeightPct,
    letterSpacingPx,
  };
}

function inferFontWeight(style: Record<string, IntentValue>): string {
  const v = style.fontWeight;
  if (!v) return "Regular";
  const n = v.kind === "number" ? v.value : v.kind === "string" ? parseInt(v.value, 10) : NaN;
  if (n >= 800) return "ExtraBold";
  if (n >= 700) return "Bold";
  if (n >= 600) return "SemiBold";
  if (n >= 500) return "Medium";
  return "Regular";
}

function numVal(v: IntentValue | undefined): number | null {
  if (!v) return null;
  if (v.kind === "number") return v.value;
  if (v.kind === "string") {
    const n = parseFloat(v.value);
    return Number.isFinite(n) ? n : null;
  }
  return null;
}

function strVal(v: IntentValue | undefined): string | null {
  if (!v) return null;
  if (v.kind === "string") return v.value;
  return null;
}
