import type {
  IntentArtboard,
  IntentNode,
  IntentValue,
} from "@cdf/core";
import { alphaOf, colorExpr, parsePadding } from "./auto-layout-rules.js";

export interface EmitUseFigmaOptions {
  /** Page node id to target (e.g. "6504:2" for _staging). */
  pageId: string;
  /** Font family used throughout the bundle. Default "Urbanist". */
  fontFamily?: string;
  /** Weights to load. Default: Regular, Medium, SemiBold, Bold, ExtraBold. */
  fontWeights?: string[];
  /** Origin (x,y) for the root frame on the page. Default (100, 100). */
  origin?: { x: number; y: number };
}

/**
 * Emit a JavaScript string ready to feed to the `use_figma` tool.
 *
 * The generated script:
 *   1. Switches to the target page (await setCurrentPageAsync)
 *   2. Loads all required font weights
 *   3. Defines helpers (hex parsing already inlined as object literals)
 *   4. Walks the IntentNode tree and emits createFrame / createText calls,
 *      respecting all the silent rules in auto-layout-rules.ts:
 *        - parent.appendChild(child) BEFORE child.layoutSizing{H,V} = 'FILL'
 *        - resize() BEFORE primaryAxisSizingMode setters
 *        - fonts loaded before createText
 *        - effects with visible:true + blendMode:'NORMAL'
 *   5. Returns the array of created node IDs
 */
export function emitUseFigma(intent: IntentArtboard, options: EmitUseFigmaOptions): string {
  const family = options.fontFamily ?? "Urbanist";
  const weights = options.fontWeights ?? ["Regular", "Medium", "SemiBold", "Bold", "ExtraBold"];
  const origin = options.origin ?? { x: 100, y: 100 };

  const ctx: EmitContext = { idSeq: 0, lines: [], createdIds: [] };

  emitHeader(ctx, options.pageId, family, weights);
  const rootVar = emitNode(ctx, intent.root, null, intent.size);
  if (rootVar) {
    ctx.lines.push(`${rootVar}.x = ${origin.x};`);
    ctx.lines.push(`${rootVar}.y = ${origin.y};`);
  }
  emitFooter(ctx);

  return ctx.lines.join("\n");
}

interface EmitContext {
  idSeq: number;
  lines: string[];
  createdIds: string[];
}

function fresh(ctx: EmitContext, prefix: string): string {
  ctx.idSeq += 1;
  return `${prefix}${ctx.idSeq}`;
}

function emitHeader(ctx: EmitContext, pageId: string, family: string, weights: string[]): void {
  ctx.lines.push(`// Auto-generated by @cdf/figma-script — DO NOT EDIT MANUALLY.`);
  ctx.lines.push(`// Rules enforced from auto-layout-rules.ts.`);
  ctx.lines.push("");
  ctx.lines.push(`const __page = figma.root.children.find(p => p.id === ${JSON.stringify(pageId)});`);
  ctx.lines.push(`if (!__page) throw new Error("Target page not found: " + ${JSON.stringify(pageId)});`);
  ctx.lines.push(`await figma.setCurrentPageAsync(__page);`);
  ctx.lines.push("");
  for (const w of weights) {
    ctx.lines.push(`await figma.loadFontAsync({ family: ${JSON.stringify(family)}, style: ${JSON.stringify(w)} });`);
  }
  ctx.lines.push("");
  ctx.lines.push(`const __ids = [];`);
  ctx.lines.push("");
}

function emitFooter(ctx: EmitContext): void {
  ctx.lines.push("");
  ctx.lines.push(`return { createdNodeIds: __ids };`);
}

/**
 * Walk a single node. Returns the JS variable name holding the created node,
 * or null if the node didn't produce one (e.g. an unresolved expression).
 */
function emitNode(
  ctx: EmitContext,
  node: IntentNode,
  parentVar: string | null,
  rootSize?: { width: number; height: number },
): string | null {
  if (node.type === "text") {
    return emitTextNode(ctx, node, parentVar);
  }
  if (node.type === "expression") {
    return null; // unresolvable
  }

  // Detect a "text-styled div" — a div with one text child and font styles.
  if (isStyledTextWrapper(node)) {
    const inner = node.children.find(c => c.type === "text");
    if (inner) {
      return emitStyledText(ctx, node, inner, parentVar);
    }
  }

  // Generic frame
  const v = fresh(ctx, "frame_");
  ctx.lines.push("");
  ctx.lines.push(`// ${node.tag}${parentVar ? "" : "  (root)"}`);
  ctx.lines.push(`const ${v} = figma.createFrame();`);
  ctx.lines.push(`${v}.name = ${JSON.stringify(node.tag)};`);
  ctx.createdIds.push(v);

  applyFrameStyle(ctx, v, node, rootSize);

  if (parentVar) {
    ctx.lines.push(`${parentVar}.appendChild(${v});`);
    applyPostAppend(ctx, v, node);
  }

  // Children (recurse with this frame as the parent)
  for (const child of node.children) {
    if (child.type === "text" && !child.text?.trim()) continue;
    emitNode(ctx, child, v);
  }

  ctx.lines.push(`__ids.push(${v}.id);`);
  return v;
}

function emitTextNode(ctx: EmitContext, node: IntentNode, parentVar: string | null): string | null {
  if (!parentVar) return null;
  const v = fresh(ctx, "text_");
  ctx.lines.push(`const ${v} = figma.createText();`);
  ctx.lines.push(`${v}.fontName = { family: "Urbanist", style: "Regular" };`);
  ctx.lines.push(`${v}.characters = ${JSON.stringify(node.text ?? "")};`);
  ctx.lines.push(`${parentVar}.appendChild(${v});`);
  ctx.lines.push(`__ids.push(${v}.id);`);
  return v;
}

function emitStyledText(
  ctx: EmitContext,
  wrapper: IntentNode,
  text: IntentNode,
  parentVar: string | null,
): string | null {
  if (!parentVar) return null;
  const v = fresh(ctx, "text_");
  const style = wrapper.style;
  const family = "Urbanist";
  const weight = inferFontWeight(style);
  const fontSize = numVal(style.fontSize) ?? 14;

  ctx.lines.push("");
  ctx.lines.push(`// styled-text wrapper`);
  ctx.lines.push(`const ${v} = figma.createText();`);
  ctx.lines.push(`${v}.fontName = { family: ${JSON.stringify(family)}, style: ${JSON.stringify(weight)} };`);
  ctx.lines.push(`${v}.fontSize = ${fontSize};`);
  ctx.lines.push(`${v}.characters = ${JSON.stringify(text.text ?? "")};`);

  const colorVal = style.color;
  if (colorVal && colorVal.kind === "color") {
    ctx.lines.push(`${v}.fills = [{ type: "SOLID", color: ${colorExpr(colorVal.literal)}${alphaOf(colorVal.literal) < 1 ? `, opacity: ${alphaOf(colorVal.literal)}` : ""} }];`);
  }
  const textAlign = strVal(style.textAlign);
  if (textAlign === "center") ctx.lines.push(`${v}.textAlignHorizontal = "CENTER";`);
  else if (textAlign === "right") ctx.lines.push(`${v}.textAlignHorizontal = "RIGHT";`);

  ctx.lines.push(`${parentVar}.appendChild(${v});`);
  ctx.lines.push(`__ids.push(${v}.id);`);
  return v;
}

function applyFrameStyle(
  ctx: EmitContext,
  v: string,
  node: IntentNode,
  rootSize?: { width: number; height: number },
): void {
  const s = node.style;

  // Size (root gets rootSize; otherwise inferred from style)
  const w = numVal(s.width) ?? rootSize?.width;
  const h = numVal(s.height) ?? rootSize?.height;
  if (w && h) ctx.lines.push(`${v}.resize(${w}, ${h});`);
  else if (w) ctx.lines.push(`${v}.resize(${w}, ${v}.height || 1);`);
  else if (h) ctx.lines.push(`${v}.resize(${v}.width || 1, ${h});`);

  // Corner radius
  const radius = numVal(s.borderRadius);
  if (radius !== null) ctx.lines.push(`${v}.cornerRadius = ${radius};`);

  // Background → fills
  const bg = s.background ?? s.backgroundColor;
  if (bg && bg.kind === "color") {
    const opacity = alphaOf(bg.literal);
    const fillExpr =
      opacity < 1
        ? `[{ type: "SOLID", color: ${colorExpr(bg.literal)}, opacity: ${opacity} }]`
        : `[{ type: "SOLID", color: ${colorExpr(bg.literal)} }]`;
    ctx.lines.push(`${v}.fills = ${fillExpr};`);
  } else {
    // Frames default to white fill; null out if no style set
    if (!bg) ctx.lines.push(`${v}.fills = [];`);
  }

  // Padding
  const padding = strVal(s.padding);
  if (padding) {
    const p = parsePadding(padding);
    ctx.lines.push(`${v}.paddingTop = ${p.top}; ${v}.paddingRight = ${p.right}; ${v}.paddingBottom = ${p.bottom}; ${v}.paddingLeft = ${p.left};`);
  }

  // Gap
  const gap = numVal(s.gap);
  if (gap !== null) ctx.lines.push(`${v}.itemSpacing = ${gap};`);

  // Layout mode
  const direction = strVal(s.flexDirection);
  const display = strVal(s.display);
  if (direction === "column") {
    ctx.lines.push(`${v}.layoutMode = "VERTICAL";`);
  } else if (direction === "row" || display === "flex") {
    ctx.lines.push(`${v}.layoutMode = "HORIZONTAL";`);
  }

  // Alignment
  const justify = strVal(s.justifyContent);
  if (justify === "space-between") ctx.lines.push(`${v}.primaryAxisAlignItems = "SPACE_BETWEEN";`);
  else if (justify === "center") ctx.lines.push(`${v}.primaryAxisAlignItems = "CENTER";`);

  const align = strVal(s.alignItems);
  if (align === "center") ctx.lines.push(`${v}.counterAxisAlignItems = "CENTER";`);
  else if (align === "flex-end") ctx.lines.push(`${v}.counterAxisAlignItems = "MAX";`);
}

function applyPostAppend(ctx: EmitContext, v: string, node: IntentNode): void {
  const s = node.style;
  const flex = numVal(s.flex);
  if (flex && flex >= 1) {
    ctx.lines.push(`${v}.layoutGrow = ${flex};`);
  }
  const width = strVal(s.width);
  if (width === "100%") {
    ctx.lines.push(`${v}.layoutSizingHorizontal = "FILL";`);
  }
}

function isStyledTextWrapper(node: IntentNode): boolean {
  if (node.tag !== "div" && node.tag !== "span") return false;
  if (Object.keys(node.style).length === 0) return false;
  const textChildren = node.children.filter(c => c.type === "text" && (c.text ?? "").trim().length > 0);
  if (textChildren.length !== 1) return false;
  const elementChildren = node.children.filter(c => c.type === "element");
  return elementChildren.length === 0;
}

function inferFontWeight(style: Record<string, IntentValue>): string {
  const v = style.fontWeight;
  if (!v) return "Regular";
  const n = v.kind === "number" ? v.value : v.kind === "string" ? parseInt(v.value, 10) : NaN;
  if (n >= 800) return "ExtraBold";
  if (n >= 700) return "Bold";
  if (n >= 600) return "SemiBold";
  if (n >= 500) return "Medium";
  return "Regular";
}

function numVal(v: IntentValue | undefined): number | null {
  if (!v) return null;
  if (v.kind === "number") return v.value;
  if (v.kind === "string") {
    const n = parseFloat(v.value);
    return Number.isFinite(n) ? n : null;
  }
  return null;
}

function strVal(v: IntentValue | undefined): string | null {
  if (!v) return null;
  if (v.kind === "string") return v.value;
  return null;
}
